### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AJHydro** [MrMasterplan/rwklevelfiles#4]
My son is really interested in using these tools to make levels in RWK. Do you have any more detailed instructions on how to install and use it? We read through your documentation but are kind of lost at where to begin. Any help would be really appreciated!  Thank you.

**Comment by mrmasterplan** [comment]
Thank you for your interest in this. How far did you get with the instruction in the [Quick Start Guide](https://github.com/mrmasterplan/rwklevelfiles#quick-start)? There are some programs you to install from the internet, and then you need to open a terminal, also known as a command window to enter the final commands and then follow the instruction on screen. You can also reach out on [discord (link here)](https://discord.gg/sFPub2qHdw) where there is an entire community dedicated to this game.

**Comment by AJHydro** [comment]
I installed the three things, but I don't know what any of this means. I'm in command prompt right now, what do I say?

**Comment by mrmasterplan** [comment]
Based on your question I feel that you will need more personal technical guidance with the installation process than I would be able to give you on this issue page. 

While the game is aimed at a younger audience, this level editor is made by me, without any association or assistance by the game developer.  My target audience were other adult players with some degree of IT knowledge. The editor is fairly technical to work with. It is closer to game programming than to playing.

My recommendation is that you find someone who can help you with working with the command line and maybe help your son work his way into the editor. Maybe there is help to find at your library, school or local hackerspace. As a father myself, I don't think this editor is suitable for children younger than maybe 11 or 12 years.

Best of luck.
Simon

**Comment by AJHydro** [comment]
Thank you for your time, I appreciate your help.
